/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package csvtojson

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import app.softwork.serialization.csv.*
import kotlinx.serialization.encodeToString

fun main() {
    println(CSVFormat)
}
